version:  '3'
services:
  datascience-notebook:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./home-credit-default-risk:/home/jovyan/home-credit-default-risk
      - ./store-item-demand-forecasting-challenge:/home/jovyan/store-item-demand-forecasting-challenge
    ports:
      - 8888:8888
    container_name: jupyter_notebook
